### ISSUE TITLE
Index.yaml is missing in the main branch

### ISSUE THREAD

**Issue by numa1985** [tfadeyi/auth0-simple-exporter#100]
### What happened?

Hi Oluwole Fadeyi,

I was trying to add the  helm package "https://github.com/tfadeyi/auth0-simple-exporter.git" in the octopus deploy I see that the index.yaml file is missing in main branch .It's a great help that if you can add the file to main branch.

Configuration information.
++++++++++++++++
![image](https://github.com/tfadeyi/auth0-simple-exporter/assets/139448875/796f7365-73b6-4c42-83b2-249781f51b60)

Error information
++++
![image](https://github.com/tfadeyi/auth0-simple-exporter/assets/139448875/28346435-f8dc-4d0b-ac71-fe40ddc0f3d0)

Thanks
Naresh

### What should have happened?

Adding the  index.yaml file to main branch in the repo ""https://github.com/tfadeyi/auth0-simple-exporter.git" will surface our issue.

### Reproduction

Adding the  index.yaml file to main branch in the repo ""https://github.com/tfadeyi/auth0-simple-exporter.git" will surface our issue.

**Comment by tfadeyi** [comment]
Hi @numa1985 thank you for raising the issue!

the index.yaml I present in a different branch https://github.com/tfadeyi/auth0-simple-exporter/tree/gh-pages, could you point the tool to that branch?

This is due to the default behaviour of https://github.com/helm/chart-releaser-action

**Comment by numa1985** [comment]
Hi Oluwole Fadeyi,

Thanks for the update!!


I configured to gh-pages (https://github.com/tfadeyi/auth0-simple-exporter/tree/gh-pages ) branch and landed up with below error. 

![image](https://github.com/tfadeyi/auth0-simple-exporter/assets/139448875/c8c64f20-9ab3-42fd-a3dd-a76bd5374b56)

Error info
+++++
![image](https://github.com/tfadeyi/auth0-simple-exporter/assets/139448875/c6b43972-b434-49e2-b565-d909c90388f9)


Best Regards
Naresh

**Comment by tfadeyi** [comment]
Maybe try https://tfadeyi.github.io/auth0-simple-exporter instead

**Comment by tfadeyi** [comment]
I'll mark the issue as resolved👍
