### ISSUE TITLE
Can't able to login to the pod with any of the shell and as well can't able to fetch the details from cluster DNS .

### ISSUE THREAD

**Issue by numa1985** [tfadeyi/auth0-simple-exporter#102]
### What happened?

Hi @tfadeyi ,

I tried to login into the pod with all the shell types but its not allowing me due to below error.

As well I can't able to fetch the metrics using the cluster DNS service but can able fetch the metrics using pod ip which is not viable solution since when ever the pods gets restarted ip gets changed.

Details
++++
ubuntu@NARU-Pr5530:~$ kubectl get all -n auth0-exporter -o wide
NAME                                  READY   STATUS    RESTARTS   AGE   IP             NODE                            NOMINATED NODE   READINESS GATES
pod/auth0-exporter-5cd568554f-56n6f   1/1     Running   0          63m   10.102.0.175   aks-npus1-35797634-vmss000012   <none>           <none>

NAME                     TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)    AGE   SELECTOR
service/auth0-exporter   ClusterIP   10.0.16.60   <none>        9301/TCP   63m   app.kubernetes.io/instance=auth0-exporter,app.kubernetes.io/name=auth0-exporter

NAME                             READY   UP-TO-DATE   AVAILABLE   AGE   CONTAINERS       IMAGES                                         SELECTOR
deployment.apps/auth0-exporter   1/1     1            1           63m   auth0-exporter   ghcr.io/tfadeyi/auth0-simple-exporter:v0.2.0   app.kubernetes.io/instance=auth0-exporter,app.kubernetes.io/name=auth0-exporter

NAME                                        DESIRED   CURRENT   READY   AGE   CONTAINERS       IMAGES                                         SELECTOR
replicaset.apps/auth0-exporter-5cd568554f   1         1         1       63m   auth0-exporter   ghcr.io/tfadeyi/auth0-simple-exporter:v0.2.0   app.kubernetes.io/instance=auth0-exporter,app.kubernetes.io/name=auth0-exporter,pod-template-hash=5cd568554f

ubuntu@NARU-Pr5530:~$ curl 10.102.0.175:9301
<html>
                        <head><title>Auth0 Exporter</title></head>
                        <body>
                        <h1>Auth0 Exporter</h1>
                        <p><a href="metrics">Metrics</a></p>
                        </body>
                        </html>

Error info
++++
1.While logging into pod
ubuntu@NARU-Pr5530:~$ kubectl -n auth0-exporter exec -it auth0-exporter-5cd568554f-56n6f -- /bin/sh
E1013 15:38:25.633638    3978 v3.go:79] EOF
                                           error: Internal error occurred: error executing command in container: failed to exec in container: failed to start exec "168543fac3fe091fbc2f97711b01857e79a4b1d48993e7401cccd36be6d91352": OCI runtime exec failed: exec failed: unable to start container process: exec: "/bin/sh": stat /bin/sh: no such file or directory: unknown

2. While fetching metrics using cluster service.(tried same with curl but same error)
ubuntu@NARU-Pr5530:~$ wget auth0-exporter-auth0-exporter.auth0-exporter.svc.cluster.local:9301
--2023-10-13 15:39:29--  http://auth0-exporter-auth0-exporter.auth0-exporter.svc.cluster.local:9301/
Resolving auth0-exporter-auth0-exporter.auth0-exporter.svc.cluster.local (auth0-exporter-auth0-exporter.auth0-exporter.svc.cluster.local)... failed: Name or service not known.
wget: unable to resolve host address ‘auth0-exporter-auth0-exporter.auth0-exporter.svc.cluster.local’
ubuntu@NARU-Pr5530:~$ wget auth0-exporter.auth0-exporter.svc.cluster.local:9301
--2023-10-13 15:39:44--  http://auth0-exporter.auth0-exporter.svc.cluster.local:9301/
Resolving auth0-exporter.auth0-exporter.svc.cluster.local (auth0-exporter.auth0-exporter.svc.cluster.local)... failed: Name or service not known.
wget: unable to resolve host address ‘auth0-exporter.auth0-exporter.svc.cluster.local’

Thanks
Naresh

### What should have happened?

It's blocking my testing for scrapping metrics into prometheus & Grafana loki

### Reproduction

I tried to login into the pod with all the shell types but its not allowing me due to below error.

As well I can't able to fetch the metrics using the cluster DNS service but can able fetch the metrics using pod ip which is not viable solution since when ever the pods gets restarted ip gets changed.

Details
++++
ubuntu@NARU-Pr5530:~$ kubectl get all -n auth0-exporter -o wide
NAME                                  READY   STATUS    RESTARTS   AGE   IP             NODE                            NOMINATED NODE   READINESS GATES
pod/auth0-exporter-5cd568554f-56n6f   1/1     Running   0          63m   10.102.0.175   aks-npus1-35797634-vmss000012   <none>           <none>

NAME                     TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)    AGE   SELECTOR
service/auth0-exporter   ClusterIP   10.0.16.60   <none>        9301/TCP   63m   app.kubernetes.io/instance=auth0-exporter,app.kubernetes.io/name=auth0-exporter

NAME                             READY   UP-TO-DATE   AVAILABLE   AGE   CONTAINERS       IMAGES                                         SELECTOR
deployment.apps/auth0-exporter   1/1     1            1           63m   auth0-exporter   ghcr.io/tfadeyi/auth0-simple-exporter:v0.2.0   app.kubernetes.io/instance=auth0-exporter,app.kubernetes.io/name=auth0-exporter

NAME                                        DESIRED   CURRENT   READY   AGE   CONTAINERS       IMAGES                                         SELECTOR
replicaset.apps/auth0-exporter-5cd568554f   1         1         1       63m   auth0-exporter   ghcr.io/tfadeyi/auth0-simple-exporter:v0.2.0   app.kubernetes.io/instance=auth0-exporter,app.kubernetes.io/name=auth0-exporter,pod-template-hash=5cd568554f

ubuntu@NARU-Pr5530:~$ curl 10.102.0.175:9301
<html>
                        <head><title>Auth0 Exporter</title></head>
                        <body>
                        <h1>Auth0 Exporter</h1>
                        <p><a href="metrics">Metrics</a></p>
                        </body>
                        </html>

Error info
++++
1.While logging into pod
ubuntu@NARU-Pr5530:~$ kubectl -n auth0-exporter exec -it auth0-exporter-5cd568554f-56n6f -- /bin/sh
E1013 15:38:25.633638    3978 v3.go:79] EOF
                                           error: Internal error occurred: error executing command in container: failed to exec in container: failed to start exec "168543fac3fe091fbc2f97711b01857e79a4b1d48993e7401cccd36be6d91352": OCI runtime exec failed: exec failed: unable to start container process: exec: "/bin/sh": stat /bin/sh: no such file or directory: unknown

2. While fetching metrics using cluster service.(tried same with curl but same error)
ubuntu@NARU-Pr5530:~$ wget auth0-exporter-auth0-exporter.auth0-exporter.svc.cluster.local:9301
--2023-10-13 15:39:29--  http://auth0-exporter-auth0-exporter.auth0-exporter.svc.cluster.local:9301/
Resolving auth0-exporter-auth0-exporter.auth0-exporter.svc.cluster.local (auth0-exporter-auth0-exporter.auth0-exporter.svc.cluster.local)... failed: Name or service not known.
wget: unable to resolve host address ‘auth0-exporter-auth0-exporter.auth0-exporter.svc.cluster.local’
ubuntu@NARU-Pr5530:~$ wget auth0-exporter.auth0-exporter.svc.cluster.local:9301
--2023-10-13 15:39:44--  http://auth0-exporter.auth0-exporter.svc.cluster.local:9301/
Resolving auth0-exporter.auth0-exporter.svc.cluster.local (auth0-exporter.auth0-exporter.svc.cluster.local)... failed: Name or service not known.
wget: unable to resolve host address ‘auth0-exporter.auth0-exporter.svc.cluster.local’

**Comment by tfadeyi** [comment]
Hey @numa1985 thank you for opening the issue.
The docker image is quite minimal you won’t be able to exec into the pod as it’s mostly just the binary in the image.

Could you type on your terminal the following.

kubectl get deployment -n auth0-exporter -o yaml auth0-exporter

And post the result of it.

You may need to add the following label to your deployment pods of the the auth0-exporter.

prometheus.io/scrape: 'true'

**Comment by numa1985** [comment]
Hi @tfadeyi ,

Thanks for the update !!

Kindly find the definition below for the deployment auth0-exporter.

ubuntu@NARU-Pr5530:~$ kubectl get deployment -n auth0-exporter -o yaml auth0-exporter
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    meta.helm.sh/release-name: auth0-exporter
    meta.helm.sh/release-namespace: auth0-exporter
  creationTimestamp: "2023-10-13T12:36:52Z"
  generation: 1
  labels:
    app.kubernetes.io/instance: auth0-exporter
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: auth0-exporter
    app.kubernetes.io/version: 0.2.0
    helm.sh/chart: auth0-exporter-0.2.0
  name: auth0-exporter
  namespace: auth0-exporter
  resourceVersion: "204948662"
  uid: 2970cca1-9aba-4397-9cb9-4ee98c7ad687
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/instance: auth0-exporter
      app.kubernetes.io/name: auth0-exporter
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: auth0-exporter
        app.kubernetes.io/name: auth0-exporter
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - preference:
              matchExpressions:
              - key: kubernetes.azure.com/mode
                operator: In
                values:
                - user
            weight: 50
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/os
                operator: In
                values:
                - linux
      containers:
      - args:
        - export
        - --auth0.domain
        - https://*****.eu.auth0.com/api/v2/
        - --web.listen-address
        - "9301"
        - --tls.disabled
        env:
        - name: TOKEN
          valueFrom:
            secretKeyRef:
              key: token
              name: auth0-credentials
        - name: CLIENT_ID
          valueFrom:
            secretKeyRef:
              key: clientId
              name: auth0-credentials
        - name: CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              key: clientSecret
              name: auth0-credentials
        image: ghcr.io/tfadeyi/auth0-simple-exporter:v0.2.0
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: http
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: auth0-exporter
        ports:
        - containerPort: 9301
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: http
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: 50m
            memory: 512Mi
          requests:
            cpu: 25m
            memory: 64Mi
        securityContext:
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 1000
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: auth0-exporter
      serviceAccountName: auth0-exporter
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2023-10-13T12:36:57Z"
    lastUpdateTime: "2023-10-13T12:36:57Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2023-10-13T12:36:52Z"
    lastUpdateTime: "2023-10-13T12:36:57Z"
    message: ReplicaSet "auth0-exporter-5cd568554f" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1


Thanks
Naresh

**Comment by numa1985** [comment]
[auth0-deployment.txt](https://github.com/tfadeyi/auth0-simple-exporter/files/12896834/auth0-deployment.txt)

**Comment by tfadeyi** [comment]
Can you use octopus deploy to set template values? Like it says here https://octopus.com/docs/deployments/kubernetes/helm-update#template-values

If yes set "labels" as the key and try set prometheus.io/scrape: 'true'. As the value

**Comment by numa1985** [comment]
Hi @tfadeyi ,

I had enabled the values for the helm chart ,it got reflected in helm release but the values hasn't got affected in deployment and we don't have any control on the deployment manifest . Kindly find the details below .

![image](https://github.com/tfadeyi/auth0-simple-exporter/assets/139448875/f169cd9e-dd7d-46b4-8948-bb2e544fc3e4)

ubuntu@NARU-Pr5530:~$ helm ls -n auth0-exporter
NAME            NAMESPACE       REVISION        UPDATED                                 STATUS          CHART                   APP VERSION
auth0-exporter  auth0-exporter  1               2023-10-13 18:08:01.09585729 +0000 UTC  deployed        auth0-exporter-0.2.0    0.2.0

ubuntu@NARU-Pr5530:~$ helm get values auth0-exporter -n auth0-exporter
USER-SUPPLIED VALUES:
affinity:
  nodeAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
    - preference:
        matchExpressions:
        - key: kubernetes.azure.com/mode
          operator: In
          values:
          - user
      weight: 50
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/os
          operator: In
          values:
          - linux
args:
- export
- --auth0.domain
- <change_me>.eu.auth0.com
- --web.listen-address
- "9301"
auth0:
  domain: https://***********.eu.auth0.com/api/v2/
  token: *****************************************
auth0-exporter: null
exporter:
  tls:
    createSecret: false
    disabled: true
image:
  pullPolicy: IfNotPresent
  repository: ghcr.io/tfadeyi/auth0-simple-exporter
  tag: v0.2.0
prometheus.io/scrape: "true"
resources:
  limits:
    cpu: 50m
    memory: 512Mi
  requests:
    cpu: 25m
    memory: 64Mi

[auth0-deployment-updated.txt](https://github.com/tfadeyi/auth0-simple-exporter/files/12897263/auth0-deployment-updated.txt)


BR,
Naresh

**Comment by tfadeyi** [comment]
Thank you for the details, I'll look into. In the meantime when updating the values in Octopus deploy could try adding

```
labels:
 -  prometheus.io/scrape: "true"
```

instead of 

```
prometheus.io/scrape: "true"
```

**Comment by numa1985** [comment]
Hi @tfadeyi : Thanks for the details and support.

Had enabled the labels for Prometheus as mentioned and ran into below error.

![image](https://github.com/tfadeyi/auth0-simple-exporter/assets/139448875/5b4ab494-d9ad-4cd6-b5ba-5d645cdcf70c)


Even when I tried doing this manually got stuck with the same error.

ubuntu@NARU-Pr5530:~$ helm upgrade auth0-exporter auth0-exporter/auth0-exporter --install --create-namespace -n auth0-exporter \
--set auth0.domain="$DOMAIN" \
--set auth0.token="$TOKEN" \
--set exporter.tls.disabled=true \
--set image.repository="ghcr.io/tfadeyi/auth0-simple-exporter" \
--set image.pullPolicy="IfNotPresent" \
--set image.tag="v0.2.0" \
--set affinity.nodeAffinity.requiredDuringSchedulingIgnoredDuringExecution.nodeSelectorTerms[0].matchExpressions[0].key="kubernetes.io/hostname" \
--set affinity.nodeAffinity.requiredDuringSchedulingIgnoredDuringExecution.nodeSelectorTerms[0].matchExpressions[0].operator="In" \
--set affinity.nodeAffinity.requiredDuringSchedulingIgnoredDuringExecution.nodeSelectorTerms[0].matchExpressions[0].values[0]="aks-npu1-16061318-vmss000000" \
--set labels[0].name="prometheus.io/scrape" \
--set labels[0].value="true"
Release "auth0-exporter" does not exist. Installing it now.
Error: YAML parse error on auth0-exporter/templates/secret.yaml: error converting YAML to JSON: yaml: line 9: did not find expected key


BR,
Naresh

**Comment by tfadeyi** [comment]
Could you remove my previous suggestion and try add this to your values file.

podAnnotations:
  prometheus.io/scrape: "true"

It was supposed to be an annotation

**Comment by tfadeyi** [comment]
@numa1985 Can check the pod logs?

kubectl logs auth0-exporter-6454cdd985-7dxvf -n auth0-exporter

**Comment by numa1985** [comment]
@tfadeyi  : you are right ,seems the token got expired.
Need to get updated token from the team tomorrow and will give a try again.

ubuntu@NARU-Pr5530:~$ kubectl logs auth0-exporter-6454cdd985-dl74s -n auth0-exporter
ts=2023-10-15T09:59:50.003Z caller=sync.go:112 level=error msg="failed to initialise exporter's connection to auth0: unable to initialise the auth0 client, check the credentials are correct." error="failed to initialise exporter's connection to auth0: unable to initialise the auth0 client, check the credentials are correct."

Thanks a million for the  support so far :)

BR,
Naresh

**Comment by numa1985** [comment]
@tfadeyi : had updated the token and tried to push the changes as mentioned .But still can't able grab metrics or resolve  using DNS.

ubuntu@NARU-Pr5530:~$ helm get values auth0-exporter -n auth0-exporter
USER-SUPPLIED VALUES:
affinity:
  nodeAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
    - preference:
        matchExpressions:
        - key: kubernetes.azure.com/mode
          operator: In
          values:
          - user
      weight: 50
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/os
          operator: In
          values:
          - linux
args:
- export
- --auth0.domain
- auth0-exporter.auth0-exporter.svc.cluster.local
- --web.listen-address
- "9301"
auth0:
  domain: https://*******.eu.auth0.com/api/v2/
  token: *************
auth0-exporter: null
exporter:
  tls:
    createSecret: false
    disabled: true
image:
  pullPolicy: IfNotPresent
  repository: ghcr.io/tfadeyi/auth0-simple-exporter
  tag: v0.2.0
podAnnotations:
  prometheus.io/scrape: "true"
resources:
  limits:
    cpu: 50m
    memory: 512Mi
  requests:
    cpu: 25m
    memory: 64Mi

ubuntu@NARU-Pr5530:~$ kubectl get all -n auth0-exporter -o wide
NAME                                 READY   STATUS    RESTARTS   AGE     IP            NODE                            NOMINATED NODE   READINESS GATES
pod/auth0-exporter-5b8bb45b5-2jgxg   1/1     Running   0          9m11s   10.102.0.36   aks-npus1-35797634-vmss000013   <none>           <none>

NAME                     TYPE        CLUSTER-IP    EXTERNAL-IP   PORT(S)    AGE     SELECTOR
service/auth0-exporter   ClusterIP   10.0.84.117   <none>        9301/TCP   9m11s   app.kubernetes.io/instance=auth0-exporter,app.kubernetes.io/name=auth0-exporter

NAME                             READY   UP-TO-DATE   AVAILABLE   AGE     CONTAINERS       IMAGES                                         SELECTOR
deployment.apps/auth0-exporter   1/1     1            1           9m12s   auth0-exporter   ghcr.io/tfadeyi/auth0-simple-exporter:v0.2.0   app.kubernetes.io/instance=auth0-exporter,app.kubernetes.io/name=auth0-exporter

NAME                                       DESIRED   CURRENT   READY   AGE     CONTAINERS       IMAGES                                         SELECTOR
replicaset.apps/auth0-exporter-5b8bb45b5   1         1         1       9m12s   auth0-exporter   ghcr.io/tfadeyi/auth0-simple-exporter:v0.2.0   app.kubernetes.io/instance=auth0-exporter,app.kubernetes.io/name=auth0-exporter,pod-template-hash=5b8bb45b5





ubuntu@NARU-Pr5530:~$ wget auth0-exporter.auth0-exporter.svc.cluster.local:9301
--2023-10-16 11:05:09--  http://auth0-exporter.auth0-exporter.svc.cluster.local:9301/
Resolving auth0-exporter.auth0-exporter.svc.cluster.local (auth0-exporter.auth0-exporter.svc.cluster.local)... failed: Name or service not known.
wget: unable to resolve host address ‘auth0-exporter.auth0-exporter.svc.cluster.local’
ubuntu@NARU-Pr5530:~$ wget 10.102.0.36:9301
--2023-10-16 11:05:17--  http://10.102.0.36:9301/
Connecting to 10.102.0.36:9301... connected.
HTTP request sent, awaiting response... 200 OK
Length: 151 [text/html]
Saving to: ‘index.html’

index.html                               100%[=================================================================================>]     151  --.-KB/s    in 0s

2023-10-16 11:05:18 (6.49 MB/s) - ‘index.html’ saved [151/151]

ubuntu@NARU-Pr5530:~$
[auth0-deploy-latest.txt](https://github.com/tfadeyi/auth0-simple-exporter/files/12914338/auth0-deploy-latest.txt)

**Comment by tfadeyi** [comment]
I'll try reproduce the issue, how was Prometheus deployed to the cluster? Helm?

Could you provide an example Prometheus configuration that you have used?

**Comment by numa1985** [comment]
@tfadeyi : I can able to fetch the metrics in Prometheus by enabling metricsEndpoint with  " auth0-exporter.auth0-exporter.svc.cluster.local" . Thanks for the support.

**Comment by tfadeyi** [comment]
I'll mention it to the project documentation
