### ISSUE TITLE
Implementing auth0-exporter in production by avoiding the static token 

### ISSUE THREAD

**Issue by numa1985** [tfadeyi/auth0-simple-exporter#104]
### Checklist

- [X] I agree to the terms within the [Code of Conduct](https://github.com/tfadeyi/auth0-simple-exporter/blob/main/CODE_OF_CONDUCT.md).

### Describe the problem you'd like to have solved

Hi @tfadeyi ,

 

We have now finished our implementation of auth0-exporter in our canary (dev) cluster using static token and would like to proceed with deploying it to production but in order to do this we would need to use client credentials to receive an access token instead of declaring a static token in the yaml configuration.

Do you support this already or will it require some implementing?

The documentation for this functionality can be found here: https://auth0.com/docs/secure/tokens/access-tokens/get-management-api-access-tokens-for-production

### Describe the ideal solution

For production cluster ,we would need to use client credentials to receive an access token instead of declaring a static token in the yaml configuration. Since for production the expiration of access token persists only for 24 hours and this is ideal as per documentation.

**Comment by tfadeyi** [comment]
Hi @numa1985 client credentials are available https://github.com/tfadeyi/auth0-simple-exporter/blob/main/deploy/charts/auth0-exporter/README.md

Helm values are present to set clientID and clientSecret.

**Comment by numa1985** [comment]
Hi @tfadeyi ,

Thanks a lot for details .
We had tested and it worked fine with the client secrets.

BR,
Naresh
