### ISSUE TITLE
Grants required for auth0-exporter to fetch log information/metrics from production Auth0 management API

### ISSUE THREAD

**Issue by numa1985** [tfadeyi/auth0-simple-exporter#105]
### What happened?

Hi @tfadeyi ,

Kindly share the  grants that is required by auth0-exporter to fetch log information/metrics from Auth0 management API .

Thanks
Naresh 

### What should have happened?

We cannot able to fetch the metrics due to unauthorized access because of lack of grants for production Auth0 management API.

### Reproduction

Kindly share the  grants that is required by auth0-exporter to fetch log information/metrics from Auth0 management API .

**Comment by tfadeyi** [comment]
Hi @numa1985, I think the permissions needed, should be:

read:logs, read:logs_users, read:users.

**Comment by tfadeyi** [comment]
The complete set of grants: read:logs, read:clients, read:users.

The read:users is required for the metric https://github.com/tfadeyi/auth0-simple-exporter/commit/8aaca5fce8eb310c8cf3b40d27314f3aa0595cb3 to get the monthly active users.

**Comment by numa1985** [comment]
Hi @tfadeyi ,

Thanks for sharing the  information.

We implemented the mentioned grants and worked fine.

Have a great weekend ahead !!

BR,
Naresh
