### ISSUE TITLE
Incorrect implementation of metrics (from prometheus and data correctness point of view)

### ISSUE THREAD

**Issue by excavador** [tfadeyi/auth0-simple-exporter#136]
### What happened?

There is a not-so-simple to understand the issue, and I have far from ideal English.
I will do my best to explain the problem, and we observe this problem in our data (compare auth0 logs with grafana and see the incorrect data)

The context. My understanding of "how exporter works" is to double-check common ground.
1. exporter starts and remembers the "startDate."
2. each scrape exporter scans all the logs from auth0 starting from "startDate."
3. each scrape exporter resets all the counters to zero and rebuilds them from logs

The additional context - [auth0 logs data retention](https://auth0.com/docs/deploy-monitor/logs/log-data-retention)
In the "Starter" plan, the old logs disappears in 1 day.

As a result, the counter number decreased (!). Let's compare the auth0 logs and the values from Prometheus (exporter)
![auth0-exporter-logs](https://github.com/tfadeyi/auth0-simple-exporter/assets/299386/370d6d2b-f745-4d73-b0de-7812cda065f7)

As you can see, we observe only four records in the logs. Why? We have an auth0 "Starter" plan. The old values disappeared.

What could we see in the Prometheus?

![auth0-exporter-metric](https://github.com/tfadeyi/auth0-simple-exporter/assets/299386/3341fa9f-b5f4-45b3-82ae-65e69b46795e)

This needs to be corrected. The counter in the Prometheus could break the monotonous, but due to the exporter restart, the counter must be zero after that!

Consider two possible situations, both of them must work correctly, but it is impossible to achieve both situations at the same time with the current implementation of exporter
1. Exporter restarted. The counter value after that is not zero but "log event count for the last 24 hours".
2. Log records disappeared. The counter value after that was not zero and decreased.

Take a look to graph above - you could see, how exporter after restart start to show the different value. There is an artifact on how auth0 works with log retentions.
In other words - imagine that some auth0 log event disappeared and **at the same time** we have two signups.
As a result, the counter will be INCREASED TO ONE instead of TWO. Until you made restart of exporter you will have problem with the data. As the result, you must restart exporter each 24 hours, otherwise you will aggregate the mistake in data
For prometheus impossible to distinguish "exporter restart" and "log data dissapperance".
The current logic will work ONLY if auth0 ALWAYS provides the full logs.
Because of that, you see the difference in data before and after the restart of the exporter, and it breaks the logic of "how the counter should work in Prometheus."

If you try to create a dashboard for this data by using `increase`, you will see the weird data. Instead of observation of "4" signups (take a look at raw "logs" above), you will observe... how many? 8 signups? 10 signups?

![auth0-exporter-grafana](https://github.com/tfadeyi/auth0-simple-exporter/assets/299386/d353f1e7-ab75-4813-963a-bf43b277a1bb)

In addition to that problem, even if you have all the auth0 logs, **each scrapes you are scanning all the logs**

### What should have happened?

From my point of view, the optimal way to achieve the target "show correct data" is the following.
- You need to remove "startTime" from the exporter 
- You should never reset counters in the exporter
- You should remember "checkpoint" variable, and on each scrape scan the logs only from the latest checkpoint.

As the result
- Exporter just after start always shows zero values in counters
- Breaks in monotonous means "exported was restarted"
- Exporter will scan only the latest logs event (and each log event will be processed once)

After that exporter will always show the correct data, and does not matter which auth0 plan you are using and how long auth0 preserve the logs

### Reproduction

Try to use auth0 Starter plan and observe the issue. I provided screenshots to support my explanation

**Comment by tfadeyi** [comment]
Thank you very much for the detailed issue! I really thought the log retention period was 30days for all tenants. I'll try spend some time during the end of week. I feel solving this might help closing some other issues.

**Comment by excavador** [comment]
> Thank you very much for the detailed issue! I really thought the log retention period was 30days for all tenants. I'll try spend some time during the end of week. I feel solving this might help closing some other issues.

I am happy to help on why possible way - by testing or expertise.

I could make a room - just create meeting in Google Calendar for o.tsarev@truvity.com

Prometheus is complex and hard to learn & understand, I will be happy to share with your my knowledge or help to to find the best possible solution

**Comment by dmotterlini** [comment]
FYI @tfadeyi I'm currently working on a possible fix for the problems outlined here, and I will post my results in a PR shortly
