### ISSUE TITLE
Add more information for docker setup

### ISSUE THREAD

**Issue by Mbaoma** [tfadeyi/auth0-simple-exporter#234]
### Checklist

- [X] I agree to the terms within the [Code of Conduct](https://github.com/tfadeyi/auth0-simple-exporter/blob/main/CODE_OF_CONDUCT.md).

### Describe the problem you'd like to have solved

I needed to use this in my docker-compose configuration, but the documentation's docker setup section was not very helpful.

### Describe the ideal solution

The ideal solution is documentation which uses the exporter in a docker environment.

### Alternatives and current workarounds

I solved this issue already. Will open a PR.

**Comment by tfadeyi** [comment]
Thank you for raising the ticket and making the PR! I didn't consider the docker-compose use case.
