### ISSUE TITLE
Monitor Monthly Active Users

### ISSUE THREAD

**Issue by houserx-ioannis** [tfadeyi/auth0-simple-exporter#90]
### Checklist

- [X] I agree to the terms within the [Code of Conduct](https://github.com/tfadeyi/auth0-simple-exporter/blob/main/CODE_OF_CONDUCT.md).

### Describe the problem you'd like to have solved

Hello!

This library is great for exporting client-specific event statistics from auth0 to prometheus. 

I would like to extend it to expose also tenant-specific metrics, such as Monthly Active Users. Such metrics are of interest to monitor alongside the log metrics, as they affect the cost incurred by auth0. 

If that extension is of interest, I can also take a look myself and opening a PR.

Many thanks!

### Describe the ideal solution

tenant-specific metrics are exposed alongside with log metrics. Monthly active users can be used as a prototype of such a solution.

### Alternatives and current workarounds

Manually examine auth0 statistics in the auth0 dashboard.

**Comment by tfadeyi** [comment]
Hi @houserx-ioannis Thank you for opening the a feature request! 
I think the feature propose would be in scope with the project, Is there any documentation around `tenant-specific metrics` that you mentioned? 
I welcome any contributions, so feel free to make a new fork and raise a PR!
Let me know if I can support with development.

**Comment by houserx-ioannis** [comment]
Many thanks @tfadeyi. Will open the PR today :-) 

For now, by `tenant-specific` metrics, I really have in mind user metrics (which seem to be tenant-specific). This is what I had as reference https://auth0.com/docs/api/management/v2/users/get-users so far to get the list of active users.

**Comment by tfadeyi** [comment]
@houserx-ioannis I've merged your PR!
There were some issues I didn't expect after the merge https://github.com/tfadeyi/auth0-simple-exporter/issues/93

**Comment by ioannis-klonatos** [comment]
Yeap can do, will try to open another PR today

**Comment by tfadeyi** [comment]
https://github.com/tfadeyi/auth0-simple-exporter/pull/95 closes the issue
